/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Jerzy Kasenbreg
 * Copyright (c) 2022 Angel Molina (angelmolinu@gmail.com)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#ifndef _USB_DESCRIPTORS_H_
#define _USB_DESCRIPTORS_H_

#include <stdint.h>

#define UAC2_ENTITY_MIC_INPUT_TERMINAL  0x01
#define UAC2_ENTITY_MIC_FEATURE_UNIT    0x02
#define UAC2_ENTITY_MIC_OUTPUT_TERMINAL 0x03
#define UAC2_ENTITY_CLOCK               0x04

enum
{
  ITF_NUM_AUDIO_CONTROL = 0,
  ITF_NUM_AUDIO_STREAMING_MIC,
  ITF_NUM_CDC,
  ITF_NUM_CDC_DATA,
  ITF_NUM_VENDOR,
  ITF_NUM_TOTAL
};

enum
{
  VENDOR_REQUEST_WEBUSB = 1,
  VENDOR_REQUEST_MICROSOFT = 2,
  VENDOR_REQUEST_SET_CLK_FREQ = 3,
  VENDOR_REQUEST_GET_CLK_FREQ = 4,
  VENDOR_REQUEST_SET_TLV320_GAIN = 5,
  VENDOR_REQUEST_GET_PLL_LOCK = 6
};

extern uint8_t const desc_ms_os_20[];

#define TUD_AUDIO_MIC_STEREO_DESC_LEN (TUD_AUDIO20_DESC_IAD_LEN\
    + TUD_AUDIO20_DESC_STD_AC_LEN\
    + TUD_AUDIO20_DESC_CS_AC_LEN\
    + TUD_AUDIO20_DESC_CLK_SRC_LEN\
    + TUD_AUDIO20_DESC_INPUT_TERM_LEN\
    + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN\
    + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(2)\
    + TUD_AUDIO20_DESC_STD_AS_LEN\
    + TUD_AUDIO20_DESC_STD_AS_LEN\
    + TUD_AUDIO20_DESC_CS_AS_INT_LEN\
    + TUD_AUDIO20_DESC_TYPE_I_FORMAT_LEN\
    + TUD_AUDIO20_DESC_STD_AS_ISO_EP_LEN\
    + TUD_AUDIO20_DESC_CS_AS_ISO_EP_LEN)

#define TUD_AUDIO_MIC_STEREO_DESCRIPTOR(_itfnum, _stridx, _epin, _epsize) \
    TUD_AUDIO20_DESC_IAD((_itfnum), 0x02, 0x00),\
    TUD_AUDIO20_DESC_STD_AC((_itfnum), 0x00, (_stridx)),\
    TUD_AUDIO20_DESC_CS_AC(0x0200, AUDIO20_FUNC_MICROPHONE, TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(2), AUDIO20_CS_AS_INTERFACE_CTRL_LATENCY_POS),\
    TUD_AUDIO20_DESC_CLK_SRC(UAC2_ENTITY_CLOCK, AUDIO20_CLOCK_SOURCE_ATT_INT_FIX_CLK, (AUDIO20_CTRL_R << AUDIO20_CLOCK_SOURCE_CTRL_CLK_FRQ_POS), UAC2_ENTITY_MIC_INPUT_TERMINAL, 0x00),\
    TUD_AUDIO20_DESC_INPUT_TERM(UAC2_ENTITY_MIC_INPUT_TERMINAL, AUDIO_TERM_TYPE_IN_GENERIC_MIC, UAC2_ENTITY_MIC_OUTPUT_TERMINAL, UAC2_ENTITY_CLOCK, 0x02, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, (AUDIO20_CTRL_R << AUDIO20_IN_TERM_CTRL_CONNECTOR_POS), 0x00),\
    TUD_AUDIO20_DESC_OUTPUT_TERM(UAC2_ENTITY_MIC_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, UAC2_ENTITY_MIC_INPUT_TERMINAL, UAC2_ENTITY_MIC_FEATURE_UNIT, UAC2_ENTITY_CLOCK, 0x0000, 0x00),\
    TUD_AUDIO20_DESC_FEATURE_UNIT(UAC2_ENTITY_MIC_FEATURE_UNIT, UAC2_ENTITY_MIC_INPUT_TERMINAL, 0x00, (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS)),\
    TUD_AUDIO20_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1U), 0x00, 0x00, 0x00),\
    TUD_AUDIO20_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1U), 0x01, 0x01, 0x00),\
    TUD_AUDIO20_DESC_CS_AS_INT(UAC2_ENTITY_MIC_OUTPUT_TERMINAL, AUDIO20_CTRL_NONE, AUDIO20_FORMAT_TYPE_I, AUDIO20_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, 0x00),\
    TUD_AUDIO20_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX),\
    TUD_AUDIO20_DESC_STD_AS_ISO_EP((_epin), (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), (_epsize), 0x01),\
    TUD_AUDIO20_DESC_CS_AS_ISO_EP(AUDIO20_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO20_CTRL_NONE, AUDIO20_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000)

#endif
